### ISSUE TITLE
Two editable scan lists are not supported yet

### ISSUE THREAD

**Issue by pawol** [sq5bpf/uvk5-reverse-engineering#7]
Two editable scan lists are not supported yet.
In the original CPS it is possible to edit two scan lists.
At the moment I see it is possible to select default scan list, set priority channel only.

**Comment by sq5bpf** [comment]
Yes, they are supported, just like in the original vendor software. 

Channel scanlist membership is in the channel settings

**Comment by pawol** [comment]
![Capture](https://github.com/sq5bpf/uvk5-reverse-engineering/assets/13277626/0d53a32a-45df-47d3-9ad0-1c553c0991cf)

**Comment by sq5bpf** [comment]
It's in the channel extra settings. Right click on channel and see properties.

If you have chirp-next 20230611 or later, then you can also enable View -> Show Extra Fields , to show these settings in the channel table without right-clicking

**Comment by sq5bpf** [comment]
It is intuitive, scanlist membership should be part of the channel settings. 
So far two people tested it, and found all options without telling them how this works, so it works at least for some (66% with 3 people sample size).

What was not intuitive is the extra settings not being shown on the channel table. This was however fixed by the chirp developers by adding the  new  View -> Show Extra Fields option. Some people don't like it, so it's not on by default.

Also keep in mind that i'm not writing a new UI to program the radio, but rather have to use what's already implemented n chirp, and go by it's design philosophy.
